export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  OPERADOR: 'OPERADOR',
  REPARTIDOR: 'REPARTIDOR',
  CIUDADANO: 'CIUDADANO',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ALL_ROLES: Role[] = Object.values(ROLES);

export const PERMISSIONS = {
  USERS_MANAGE: 'users.manage',
  CLIENTS_READ: 'clients.read',
  CLIENTS_CREATE: 'clients.create',
  CLIENTS_UPDATE: 'clients.update',
  PRODUCTS_READ: 'products.read',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRICING_READ: 'pricing.read',
  PRICING_MANAGE: 'pricing.manage',
  PRICING_QUOTE: 'pricing.quote',
  ORDERS_READ: 'orders.read',
  ORDERS_CREATE: 'orders.create',
  ORDERS_UPDATE: 'orders.update',
  ORDERS_CANCEL: 'orders.cancel',
  ORDERS_SELF: 'orders.self',
  DELIVERY_READ: 'delivery.read',
  DELIVERY_CLAIM: 'delivery.claim',
  DELIVERY_UPDATE: 'delivery.update',
  DELIVERY_CREATE: 'delivery.create',
  STOCK_READ: 'stock.read',
  STOCK_MANAGE: 'stock.manage',
  ACCOUNTS_READ: 'accounts.read',
  ACCOUNTS_ADJUST: 'accounts.adjust',
  ACCOUNTS_REVERSE: 'accounts.reverse',
  ACCOUNTS_SELF: 'accounts.self',
  CLIENTS_SELF: 'clients.self',
  CLIENTS_LINK_USER: 'clients.linkUser',
  PAYMENTS_READ: 'payments.read',
  PAYMENTS_REVIEW: 'payments.review',
  PAYMENTS_REVERSE: 'payments.reverse',
  PAYMENTS_SELF: 'payments.self',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: Permission[] = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: [...ALL_PERMISSIONS],
  ADMIN: [
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.CLIENTS_LINK_USER,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.PRICING_READ,
    PERMISSIONS.PRICING_MANAGE,
    PERMISSIONS.PRICING_QUOTE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.ORDERS_CANCEL,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_REVIEW,
    PERMISSIONS.PAYMENTS_REVERSE,
    PERMISSIONS.DELIVERY_READ,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.ACCOUNTS_READ,
    PERMISSIONS.ACCOUNTS_ADJUST,
    PERMISSIONS.ACCOUNTS_REVERSE,
  ],
  OPERADOR: [
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_CREATE,
    PERMISSIONS.CLIENTS_UPDATE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.PRICING_READ,
    PERMISSIONS.PRICING_QUOTE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.DELIVERY_READ,
    PERMISSIONS.STOCK_READ,
    PERMISSIONS.ACCOUNTS_READ,
    PERMISSIONS.ACCOUNTS_ADJUST,
  ],
  REPARTIDOR: [
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRICING_QUOTE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.DELIVERY_READ,
    PERMISSIONS.DELIVERY_CLAIM,
    PERMISSIONS.DELIVERY_UPDATE,
    PERMISSIONS.DELIVERY_CREATE,
    PERMISSIONS.ACCOUNTS_READ,
  ],
  CIUDADANO: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRICING_QUOTE,
    PERMISSIONS.ACCOUNTS_SELF,
    PERMISSIONS.CLIENTS_SELF,
    PERMISSIONS.PAYMENTS_SELF,
    PERMISSIONS.ORDERS_SELF,
  ],
};

export function defaultPermissionsForRole(role: Role): Permission[] {
  return [...ROLE_PERMISSIONS[role]];
}
