import mongoose, { Schema, Document, Model, Types } from 'mongoose';
import {
  ALL_DIRECTIONS,
  ALL_MOVEMENT_TYPES,
  ALL_SOURCE_TYPES,
  type Direction,
  type MovementType,
  type SourceType,
} from './accounts.types.js';

export interface AccountMovementDocument extends Document {
  _id: Types.ObjectId;
  clientId: Types.ObjectId;
  direction: Direction;
  amountMinor: number;
  movementType: MovementType;
  description: string;
  occurredAt: Date;
  sourceType: SourceType;
  sourceId?: Types.ObjectId | null;
  idempotencyKey?: string | null;
  reversesMovementId?: Types.ObjectId | null;
  createdBy?: Types.ObjectId | null;
  createdAt: Date;
  updatedAt: Date;
}

interface AccountMovementModel extends Model<AccountMovementDocument> {
  /** Looks up a movement by its idempotency key, scoped to non-null keys only. */
  findByIdempotencyKey(key: string): Promise<AccountMovementDocument | null>;
}

const accountMovementSchema = new Schema<AccountMovementDocument, AccountMovementModel>(
  {
    clientId: {
      type: Schema.Types.ObjectId,
      ref: 'Client',
      required: true,
    },
    direction: {
      type: String,
      required: true,
      enum: ALL_DIRECTIONS,
    },
    amountMinor: {
      type: Number,
      required: true,
      min: 1,
      validate: {
        validator: (v: number) => Number.isInteger(v),
        message: 'amountMinor debe ser un entero positivo',
      },
    },
    movementType: {
      type: String,
      required: true,
      enum: ALL_MOVEMENT_TYPES,
    },
    description: {
      type: String,
      required: true,
      trim: true,
      maxlength: 500,
    },
    occurredAt: {
      type: Date,
      required: true,
      default: () => new Date(),
    },
    sourceType: {
      type: String,
      required: true,
      enum: ALL_SOURCE_TYPES,
      default: 'SYSTEM',
    },
    sourceId: {
      type: Schema.Types.ObjectId,
      default: null,
    },
    idempotencyKey: {
      type: String,
      default: null,
      trim: true,
      maxlength: 200,
    },
    reversesMovementId: {
      type: Schema.Types.ObjectId,
      ref: 'AccountMovement',
      default: null,
    },
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  },
);

// Primary read paths: history of a client ordered by occurredAt desc.
accountMovementSchema.index(
  { clientId: 1, occurredAt: -1, _id: -1 },
  { name: 'clientId_occurredAt_desc' },
);

accountMovementSchema.index(
  { clientId: 1, movementType: 1, occurredAt: -1 },
  { name: 'clientId_movementType_occurredAt' },
);

// Idempotency: a given key must be globally unique across the ledger.
// Partial filter ensures we don't store empty/null keys.
accountMovementSchema.index(
  { idempotencyKey: 1 },
  {
    name: 'idempotencyKey_unique',
    unique: true,
    partialFilterExpression: { idempotencyKey: { $type: 'string' } },
  },
);

// A movement can be reversed at most once. The reversal record links back
// via reversesMovementId; uniqueness here guarantees no double reversal.
accountMovementSchema.index(
  { reversesMovementId: 1 },
  {
    name: 'reversesMovementId_unique',
    unique: true,
    partialFilterExpression: { reversesMovementId: { $type: 'objectId' } },
  },
);

accountMovementSchema.index({ createdAt: -1 }, { name: 'createdAt_desc' });

// Source lookup (e.g. "find the movement generated by Payment X"). Non-unique
// because a single source could in theory produce more than one movement in
// future flows; uniqueness is enforced at the application layer (idempotency
// keys + reverse-uniqueness on reversesMovementId).
accountMovementSchema.index(
  { sourceType: 1, sourceId: 1 },
  { name: 'sourceType_sourceId' },
);

accountMovementSchema.statics.findByIdempotencyKey = function (key: string) {
  return this.findOne({ idempotencyKey: key });
};

export const AccountMovement: AccountMovementModel =
  (mongoose.models.AccountMovement as AccountMovementModel | undefined) ??
  mongoose.model<AccountMovementDocument, AccountMovementModel>(
    'AccountMovement',
    accountMovementSchema,
  );
